import type {Skill} from './SkillLibrary';
import {useEffect,useState} from 'react';
import type {IR,Module} from '../types/model';
import type {HarnessState,EditResult,Change} from '../types/harness';
import {command} from '../types/harness';
export function DiffTable({changes}:{changes:Change[]}){return <table className="diff-table"><thead><tr><th>Component / field</th><th>Current / before</th><th>Proposed / after</th></tr></thead><tbody>{changes.map((c,i)=><tr key={i}><td>{c.path||'(root)'}<small>{c.field}</small></td><td><code>{JSON.stringify(c.before)}</code></td><td><code>{JSON.stringify(c.after)}</code></td></tr>)}</tbody></table>}
export function EditPanel({state,focus,onState,onModel}:{state:HarnessState;focus:Module;onState:(s:HarnessState)=>void;onModel:(ir:IR)=>void}){
 const node=state.architecture?.nodes.find(n=>n.latest_observed_module_id===focus.id)??state.architecture?.nodes.find(n=>n.qualified_name===focus.qualified_name);
 const [skillOptions,setSkillOptions]=useState<{skill:Skill;parameters:Record<string,unknown>}[]>([]),[skillId,setSkillId]=useState('');
 useEffect(()=>{setSkillId('');setSkillOptions([]);if(node)fetch(`/api/skills/compatible/${node.id}`).then(r=>r.json()).then(d=>setSkillOptions(d.skills??[])).catch(()=>setSkillOptions([]))},[node?.id,state.summary?.revision]);
 const [captureValues,setCaptureValues]=useState(false);
 const [parameter,setParameter]=useState(''),[value,setValue]=useState(''),[result,setResult]=useState<EditResult|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[advanced,setAdvanced]=useState(false),[raw,setRaw]=useState(''),[historyRevision,setHistoryRevision]=useState<number|null>(null),[previewed,setPreviewed]=useState(false);
 useEffect(()=>{const key=node?Object.keys(node.parameters)[0]??'':'';setParameter(key);setValue(node&&key?JSON.stringify(node.parameters[key]):'');setResult(null);setError('');setPreviewed(false)},[node?.id,state.summary?.revision]);
 if(!state.enabled)return <section className="edit-panel"><h2>Read-only observation</h2><p>A saved Model IR contains runtime evidence. Editing needs a live model and example inputs.</p><code>p2i demo transformer --edit</code><p>Or call p2i.serve(harness) from Python.</p></section>;
 const revision=state.summary!.revision;
 const action=()=>skillId?{type:'replace_with_skill',target:node?.id,skill_id:skillId,parameters:skillOptions.find(s=>s.skill.id===skillId)?.parameters??{},expected_revision:revision}:advanced?{...JSON.parse(raw),expected_revision:revision}:{type:'set_parameter',target:node?.id,parameter,value:JSON.parse(value),expected_revision:revision};
 const run=async(name:string)=>{setBusy(true);setError('');try{const body=['preview','apply'].includes(name)?action():{expected_revision:revision,capture_values:captureValues};const response=await command(name,body);onState(response.state);setResult(response.result);setPreviewed(name==='preview'&&response.result.success===true);if(response.result.model)onModel(response.result.model)}catch(e){setError(String(e));setPreviewed(false)}finally{setBusy(false)}};
 const history=state.history?.find(h=>h.revision===historyRevision);
 return <section className="edit-panel"><div className="edit-intro"><span className="badge">Architecture r{revision}</span><span className="badge">Observed r{state.summary?.observed_revision??'—'}</span><h2>{node?.qualified_name||node?.name||focus.name}</h2><p>Propose a constructor change, preview its diff and run validation, then commit. Runtime evidence updates only after Build & Re-trace succeeds.</p></div>
 {!node&&<div className="readonly-note"><strong>Read-only</strong><p>No editable architecture node is bound to this observed module. It may be an adapter-managed internal or a module removed from the proposed architecture.</p></div>}
 {node&&!node.editable&&<div className="readonly-note"><strong>Read-only constructor</strong>{node.edit_restrictions.map(r=><p key={r}>{r}</p>)}<p>Whole-module replacement and wrapping remain available through structured actions when permitted.</p></div>}
 {node?.editable&&Object.keys(node.parameters).length>0&&<div className="parameter-form"><label>Constructor parameter<select aria-label="Constructor parameter" value={parameter} onChange={e=>{setParameter(e.target.value);setValue(JSON.stringify(node.parameters[e.target.value]));setPreviewed(false);setResult(null)}}>{Object.keys(node.parameters).map(key=><option key={key}>{key}</option>)}</select></label><div><small>Current value</small><code>{JSON.stringify(node.parameters[parameter])}</code></div><label>Proposed value{typeof node.parameters[parameter]==='boolean'?<select aria-label="Proposed value" value={value} onChange={e=>{setValue(e.target.value);setPreviewed(false)}}><option>true</option><option>false</option></select>:<input aria-label="Proposed value" type={typeof node.parameters[parameter]==='number'?'number':'text'} step="any" value={value} onChange={e=>{setValue(e.target.value);setPreviewed(false)}}/>}</label></div>}
 <div className="skill-replacement"><h3>Replace with Skill</h3><p>Only replacements with compatible known tensor contracts appear here. Preview also constructs and executes the proposal.</p><select aria-label="Replacement skill" value={skillId} onChange={e=>{setSkillId(e.target.value);setPreviewed(false);setResult(null)}}><option value="">Constructor edit (no skill replacement)</option>{skillOptions.map(({skill})=><option key={skill.id} value={skill.id}>{skill.name} · {skill.status}</option>)}</select>{!skillOptions.length&&<p>No verified contract-compatible default configurations. Use structured JSON with explicit parameters for other skills.</p>}</div>
 <details onToggle={e=>setAdvanced(e.currentTarget.open)}><summary>Structured action JSON (batch / replace / insert / remove / wrap)</summary><textarea aria-label="Action JSON" value={raw} placeholder={'{"type":"batch","actions":[...]}'} onChange={e=>{setRaw(e.target.value);setPreviewed(false)}}/><p className="hint">Batch edits update explicit dependent dimensions atomically. The expected revision is added automatically.</p></details>
 <label className="capture-toggle"><input type="checkbox" checked={captureValues} onChange={e=>setCaptureValues(e.target.checked)}/> Capture bounded whole-tensor CPU heatmaps on re-trace (opt-in)</label><div className="edit-actions"><button disabled={busy||(!skillId&&!advanced&&(!node?.editable||!parameter))} onClick={()=>run('preview')}>Preview & validate</button><button className="primary" disabled={busy||!previewed} onClick={()=>run('apply')}>Commit edit</button><button disabled={busy} onClick={()=>run('retrace')}>Build & Re-trace</button></div>
 {busy&&<p role="status">Constructing and validating the proposed model…</p>}{error&&<p role="alert">{error}</p>}
 {result&&<div className="validation-result" aria-live="polite"><strong>{result.success===true?'Validation passed':result.success===false?'Edit rejected':'Validation report'}</strong>{result.validation&&<p>Schema: {String(result.validation.schema_valid)} · Constructor: {String(result.validation.constructor_valid)} · Forward: {String(result.validation.forward_valid)}</p>}{result.errors?.map(e=><p role="alert" key={e}>{e}</p>)}{result.warnings?.map(e=><p key={e}>{e}</p>)}{result.diff&&<DiffTable changes={result.diff.changes}/>}</div>}
 <div className="revision-heading"><h3>Revision history</h3><button disabled={busy} onClick={()=>run('undo')}>Undo</button><button disabled={busy} onClick={()=>run('redo')}>Redo</button></div><div className="revision-list"><span>r0 · Original architecture</span>{state.history?.map(h=><button key={h.revision} onClick={()=>setHistoryRevision(h.revision)}>r{h.revision} · {h.action.type} · {h.diff.changes.length} changes</button>)}</div>{history&&<DiffTable changes={history.diff.changes}/>}
 {state.summary?.comparison!=null&&<details><summary>Observed runtime comparison</summary><pre>{JSON.stringify(state.summary.comparison,null,2)}</pre></details>}{state.summary?.weight_transfer!=null&&<details><summary>Weight transfer report</summary><pre>{JSON.stringify(state.summary.weight_transfer,null,2)}</pre></details>}
 </section>
}
