import {useEffect,useState} from 'react';
import type {IR,Module,Selection} from '../types/model';
import {shape} from '../types/model';
export function Breadcrumbs({ir,focus,select}:{ir:IR;focus:Module;select:(id:string)=>void}){
 const byid=new Map(ir.modules.map(m=>[m.id,m]));const chain:Module[]=[];const seen=new Set<string>();let current:Module|undefined=focus;
 while(current&&!seen.has(current.id)){seen.add(current.id);chain.unshift(current);current=current.parent_id?byid.get(current.parent_id):undefined}
 return <div className="breadcrumbs" aria-label="Module breadcrumbs">{chain.map((m,i)=><span key={m.id}>{i>0&&<span className="crumb-divider">/</span>}<button onClick={()=>select(m.id)} aria-current={m.id===focus.id?'location':undefined}>{m.qualified_name?m.name:ir.metadata.name}</button></span>)}</div>
}
export function ExploreOverview({ir,focus,select,compute,visible,inspect}:{ir:IR;focus:Module;select:(id:string)=>void;compute:()=>void;visible:(id:string)=>boolean;inspect?:(s:Selection)=>void}){
 const [limit,setLimit]=useState(60);
 useEffect(()=>setLimit(60),[focus.id]);
 const ts=new Map(ir.tensors.map(t=>[t.id,t]));const ms=new Map(ir.modules.map(m=>[m.id,m]));
 const children=ir.module_edges.filter(e=>e.parent_id===focus.id&&visible(e.child_id));
 const groups=children.slice(0,limit).map(edge=>{const found=new Set<string>();const visit=(id:string)=>{if(found.has(id))return;found.add(id);ms.get(id)?.children.forEach(visit)};visit(edge.child_id);const members=[...found].map(id=>ms.get(id)!);return {edge,members:found,calls:(ir.runtime?.calls??[]).filter(c=>found.has(c.module_id)),inputs:new Set(members.flatMap(m=>m.input_tensor_ids)),outputs:new Set(members.flatMap(m=>m.output_tensor_ids))}});
 const routes:{from:string;to:string;tensor:string}[]=[];
 for(const from of groups)for(const to of groups){if(from===to||[...from.members].some(id=>to.members.has(id)))continue;const shared=[...from.outputs].find(id=>to.inputs.has(id)&&from.calls.some(a=>a.output_tensor_ids.includes(id)&&to.calls.some(b=>b.sequence>a.sequence&&b.input_tensor_ids.includes(id))));if(shared)routes.push({from:from.edge.child_id,to:to.edge.child_id,tensor:shared})}
 const ownOps=ir.operations.filter(o=>o.graph==='runtime'&&o.parent_module_id===focus.id);
 const pills=(ids:string[])=><div className="shape-pills">{ids.slice(0,4).map(id=><span key={id}>{shape(ts.get(id))}</span>)}{ids.length>4&&<span>+{ids.length-4} tensors</span>}</div>;
 return <section className="explore-overview"><div className="flow-boundary"><span>OBSERVED INPUTS</span>{focus.input_tensor_ids.length?pills(focus.input_tensor_ids):<small>No tensor inputs recorded for this container</small>}</div>
 <div className="overview-title"><div><p>INSIDE THIS COMPONENT</p><h3>{children.length?`${children.length} registered children`:'Primitive computation'}</h3></div><button onClick={compute}>Explore computation →</button></div>
 <div className="architecture-flow" aria-label="Observed module tensor flow">
 {children.length>0&&<svg viewBox={`0 0 800 ${Math.ceil(Math.min(children.length,limit)/2)*205+20}`} style={{height:Math.ceil(Math.min(children.length,limit)/2)*205+20,minWidth:800}} role="group" aria-label="Discovered components and recorded connections">
 <defs><marker id="module-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8" fill="#40948b"/></marker></defs>
 {routes.slice(0,80).map((r,i)=>{const a=children.findIndex(e=>e.child_id===r.from),b=children.findIndex(e=>e.child_id===r.to);if(a<0||b<0||a>=limit||b>=limit)return null;const sameRow=Math.floor(a/2)===Math.floor(b/2);const x1=sameRow?(a%2===0?335:465):185+(a%2)*430,y1=20+Math.floor(a/2)*205+(sameRow?69:138),x2=sameRow?(b%2===0?335:465):185+(b%2)*430,y2=20+Math.floor(b/2)*205+(sameRow?69:0);const mid=(y1+y2)/2;const path=sameRow?`M${x1},${y1} L${x2},${y2}`:`M${x1},${y1} C${x1},${mid+24} ${x2},${mid-24} ${x2},${y2}`;return <g key={i} className="module-flow-edge" role="button" tabIndex={0} aria-label={`Inspect tensor ${r.tensor}`} onClick={()=>inspect?.({kind:'tensor',id:r.tensor})} onKeyDown={e=>{if(e.key==='Enter')inspect?.({kind:'tensor',id:r.tensor})}}><path d={path} fill="none" stroke="#72b3a9" strokeWidth="2" markerEnd="url(#module-arrow)"/><text x={(x1+x2)/2} y={mid-9} textAnchor="middle">{shape(ts.get(r.tensor))}</text><title>{r.tensor} · observed output-to-input identity</title></g>})}
 {children.slice(0,limit).map((e,i)=>{const m=ms.get(e.child_id)!;return <g key={e.name} className="module-flow-node" role="button" tabIndex={0} aria-label={`Explore ${m.qualified_name}`} onClick={()=>select(m.id)} onKeyDown={event=>{if(event.key==='Enter')select(m.id)}} transform={`translate(${35+(i%2)*430},${20+Math.floor(i/2)*205})`}><rect width="300" height="138" rx="14"/><text className="flow-origin" x="18" y="25">{m.origin.kind.toUpperCase()} · {m.executed?'OBSERVED':'NO DIRECT CALL'}</text><text className="flow-name" x="18" y="55">{e.name.length>28?e.name.slice(0,26)+'…':e.name}{e.shared?' ↗':''}</text><text className="flow-class" x="18" y="77">{m.class_name}</text><text className="flow-shape" x="18" y="103">{m.output_tensor_ids.length?shape(ts.get(m.output_tensor_ids[0])):'Open registered children'}</text><text className="flow-count" x="18" y="124">{m.parameter_count?.toLocaleString()??'?'} parameters</text><text className="flow-open" x="263" y="55">↗</text><title>{m.qualified_name} · {m.children.length} children · {m.call_ids.length} calls</title></g>})}
 </svg>}
 </div>
 {children.length>limit&&<p className="hint">Showing {limit} of {children.length} registered children. <button onClick={()=>setLimit(n=>n+60)}>Show more modules</button></p>}
 {children.length>0&&ownOps.length>0&&<div className="parent-operations"><strong>{ownOps.length} operations recorded directly in this module</strong><p>These operations are outside the child modules above. Open one to inspect its actual tensor connections.</p>{ownOps.slice(0,8).map(o=><button key={o.id} onClick={()=>{inspect?.({kind:'operation',id:o.id});compute()}}>{o.display_name}</button>)}{ownOps.length>8&&<button onClick={compute}>See all operations</button>}</div>}
 {routes.length>0&&<div className="module-routes"><h3>Recorded tensor routes</h3>{routes.slice(0,12).map((r,i)=><div key={i}><button onClick={()=>select(r.from)}>{ms.get(r.from)?.name}</button><span>→</span><code>{shape(ts.get(r.tensor))}</code><span>→</span><button onClick={()=>select(r.to)}>{ms.get(r.to)?.name}</button></div>)}<p className="hint">Each route matches an observed output tensor to an input in another component. Additional details remain in Compute.</p></div>}
 {!children.length&&<div className="leaf-explainer"><h3>What happened here?</h3><p>This module has no registered child modules. Inspect the actual runtime operations, tensor transformations and library implementation captured for it.</p><button onClick={compute}>Open focused computation</button></div>}
 <p className="hint">Boxes are discovered modules. Only matching observed tensors create arrows; box placement alone does not imply execution order. Containers without direct calls remain explorable.</p>
 <div className="flow-boundary output"><span>OBSERVED OUTPUTS</span>{focus.output_tensor_ids.length?pills(focus.output_tensor_ids):<small>No tensor outputs recorded for this container</small>}</div></section>
}
