import type {IR,Operation,Selection,Tensor} from '../types/model';
import {shape} from '../types/model';
import {TensorSample,emptyInspection} from './TensorSample';
import type {Inspection} from './TensorSample';
export function OperationExplainer({ir,op,select,inspection=emptyInspection,phase}:{ir:IR;op:Operation;select:(s:Selection)=>void;inspection?:Inspection;phase?:number}){
 const tensors=new Map(ir.tensors.map(t=>[t.id,t]));const kind=op.op_type.toLowerCase();
 const transform=/reshape|view|transpose|permute/.test(kind),matrix=/matmul|bmm|addmm|linear/.test(kind),conv=/conv/.test(kind),add=/aten.add\./.test(kind);
 const label=transform?'Shape transformation':matrix?'Matrix / projection':conv?'Convolution':/softmax/.test(kind)?'Softmax':add?'Elementwise addition':'Captured computation';
 const description=transform?'Compare the recorded axes before and after this operation.':matrix?'Compare the recorded input and output dimensions for this operator.':conv?'Inspect the recorded input, kernel and output dimensions.':add?'The recorded input branches meet at this addition.':'The tensors below are linked to this exact operation in the selected trace.';
 const input=tensors.get(op.input_tensor_ids[0]);
 const axes=(t:Tensor,output:boolean)=><div className="tensor-axes">{t.shape.map((d,i)=><span key={i} className={transform&&output&&input?.shape[i]!==d?'axis-changed':''}><small>axis {i}</small><b>{d??'?'}</b></span>)}</div>;
 const render=(ids:string[],output=false)=><div className="operation-tensors">{ids.slice(0,1).map((id,i)=>{const t=tensors.get(id);return <div className={`tensor-stage ${i?'secondary-tensor':''} ${phase===(output?2:0)?'tensor-active':''}`} key={id}><button onClick={()=>select({kind:'tensor',id})}><code>{output?'OUTPUT':'INPUT'} {i+1} · {id}</code><strong>{shape(t)}</strong>{t&&i===0&&axes(t,output)}<small>{t?.dtype} · {t?.device}</small></button>{t&&i===0&&<TensorSample tensor={t} sample={inspection.tensors[id]}/>}<div className="tensor-relations">{t?.producer_id&&<button onClick={()=>select({kind:'operation',id:t.producer_id!})}>Producer {t.producer_id}</button>}{t?.consumer_ids.slice(0,1).map(consumer=><button key={consumer} onClick={()=>select({kind:'operation',id:consumer})}>Consumer {consumer}</button>)}</div></div>})}{ids.length>1&&<details><summary>{ids.length-1} more tensors</summary>{ids.slice(1).map(id=><button key={id} onClick={()=>select({kind:'tensor',id})}>{id} {shape(tensors.get(id))}</button>)}</details>}</div>;
 return <section className="operation-explainer"><div className="explanation-heading"><div><p>{op.graph==='runtime'?'OBSERVED RUNTIME':'STATIC GRAPH'} · {op.call_id??'no runtime call'} · #{op.sequence}</p><h3>{label}</h3></div><code>{op.op_type}</code></div><p className="microscope-provenance">Module: {ir.modules.find(m=>m.id===op.parent_module_id)?.qualified_name||op.parent_module_id||'unknown'} · origin: {ir.modules.find(m=>m.id===op.parent_module_id)?.origin.kind??'unknown'}{op.source&&` · ${op.source.file}:${op.source.line??'?'}`}</p><p className="operation-description">{description}</p><div className="operation-flow">{render(op.input_tensor_ids)}<span className="flow-arrow">→</span><div className="operation-symbol" aria-label={label}>{matrix?'×':add?'+':transform?'⇄':conv?'⊛':'ƒ'}<small>{op.display_name.replace(/^aten\./,'').split('.')[0]}</small></div><span className="flow-arrow">→</span>{render(op.output_tensor_ids,true)}</div>{inspection.operations[op.id]!=null&&<div className="observed-arguments"><span>Recorded arguments</span><code>{JSON.stringify(inspection.operations[op.id])}</code></div>}</section>;
}
