import {useEffect,useState} from 'react';
export type Skill={id:string;name:string;kind:string;status:string;revision:number;description:string;input_contracts:unknown[];output_contracts:unknown[];hyperparameters:unknown[];origin:unknown;validation:unknown;evaluation:unknown[]};
export function SkillLibrary(){
 const [query,setQuery]=useState(''),[status,setStatus]=useState(''),[kind,setKind]=useState(''),[skills,setSkills]=useState<Skill[]>([]),[selected,setSelected]=useState<Skill|null>(null),[versions,setVersions]=useState<Skill[]>([]),[error,setError]=useState('');
 useEffect(()=>{const c=new AbortController();fetch(`/api/skills?query=${encodeURIComponent(query)}${status?`&status=${status}`:''}${kind?`&kind=${kind}`:''}`,{signal:c.signal}).then(r=>{if(!r.ok)throw Error('Skill request failed');return r.json()}).then(d=>setSkills(d.skills)).catch(e=>{if(e.name!=='AbortError')setError(String(e))});return()=>c.abort()},[query,status,kind]);
 const inspect=async(s:Skill)=>{setSelected(s);try{const r=await fetch(`/api/skills/${s.id}`);if(!r.ok)throw Error('Skill detail failed');setVersions((await r.json()).versions)}catch(e){setError(String(e))}};
 return <section className="skill-library"><p className="eyebrow">LOCAL CAPABILITIES</p><h2>Skill Library</h2><p>Reusable components with explicit contracts. The observed graph remains the runtime evidence.</p><div className="skill-filters"><input aria-label="Search skills" placeholder="Search name, description or tags" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Skill status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{['candidate','validated','evaluated','promoted','rejected','deprecated'].map(v=><option key={v}>{v}</option>)}</select><select aria-label="Skill kind" value={kind} onChange={e=>setKind(e.target.value)}><option value="">All kinds</option>{['primitive','canonical','composite','custom','discovered'].map(v=><option key={v}>{v}</option>)}</select></div>{error&&<p role="alert">{error}</p>}<div className="skill-grid">{skills.map(s=><button className={`skill-card ${selected?.id===s.id?'chosen':''}`} key={s.id} onClick={()=>inspect(s)}><span className={`badge skill-${s.status}`}>{s.status==='candidate'?(s.validation?'VALIDATION FAILED':'UNVALIDATED'):s.status.toUpperCase()}</span><h3>{s.name}</h3><code>{s.id} · r{s.revision}</code><p>{s.description}</p><small>{s.kind}</small></button>)}</div>{!skills.length&&<p>No skills match these filters.</p>}{selected&&<article className="skill-detail"><h3>{selected.name} · {selected.status}</h3>{[['Origin',selected.origin],['Input contracts',selected.input_contracts],['Output contracts',selected.output_contracts],['Hyperparameters',selected.hyperparameters],['Validation',selected.validation??'UNVALIDATED — built-in adapters are explicitly trusted; external candidates require testing.'],['Evaluation history',selected.evaluation]].map(([title,value])=><details key={String(title)} open><summary>{String(title)}</summary><pre>{JSON.stringify(value,null,2)}</pre></details>)}<h4>Versions</h4>{versions.map(s=><button key={s.revision} onClick={()=>setSelected(s)}>r{s.revision} · {s.status}</button>)}</article>}</section>
}
export function SkillBinding({skillId,revision}:{skillId:string;revision:number}){
 const [skill,setSkill]=useState<Skill|null>(null);
 useEffect(()=>{setSkill(null);fetch(`/api/skills/${skillId}`).then(r=>r.json()).then(d=>setSkill(d.versions?.find((s:Skill)=>s.revision===revision)??null)).catch(()=>setSkill(null))},[skillId,revision]);
 return <details className="skill-detail"><summary>Architecture skill · {skill?.name??skillId} · r{revision}</summary><p>{skill?.status??'Unavailable'} · separate from latest observed runtime</p><pre>{JSON.stringify(skill?{origin:skill.origin,inputs:skill.input_contracts,outputs:skill.output_contracts,hyperparameters:skill.hyperparameters,validation:skill.validation,evaluations:skill.evaluation}:null,null,2)}</pre></details>
}
