// Run against: p2i serve tiny_transformer.json --port 8000
import { chromium, expect } from '@playwright/test';
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1500,height:1000}});
const errors=[];
page.on('pageerror',e=>errors.push(String(e)));
page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('favicon'))errors.push(m.text())});
try{
 await page.goto(process.env.P2I_URL??'http://127.0.0.1:8000');
 await expect(page.getByRole('heading',{name:'TinyTransformer',exact:true}).first()).toBeVisible();
 await page.getByRole('button',{name:'Expand blocks',exact:true}).click();
 await page.getByRole('button',{name:'Expand blocks.0',exact:true}).click();
 await page.locator('.tree-name').filter({hasText:/^.*attention/}).first().click();
 await expect(page.locator('.scope h2')).toHaveText('blocks.0.attention');
 await expect(page.locator('.details')).toContainText('16,640');
 await expect(page.locator('.details')).toContainText('[2, 16, 64]');
 await expect(page.locator('.details .badge')).toHaveText('user');
 await page.getByRole('button',{name:'Computation',exact:true}).click();
 await expect(page.locator('.op-node').first()).toBeVisible();
 await page.locator('.op-node').first().click();
 await expect(page.locator('.details')).toContainText('runtime operation');
 await page.locator('.details .tensor-list button').first().click();
 await expect(page.locator('.details')).toContainText('runtime tensor');
 await expect(page.locator('.details')).toContainText('Dtype');
 await page.getByLabel('Zoom in',{exact:true}).click();
 await expect(page.locator('.graph-controls')).toContainText('120%');
 await page.locator('svg.graph').scrollIntoViewIfNeeded();
 const graph=await page.locator('svg.graph').boundingBox();
 const before=await page.locator('svg.graph > g').getAttribute('transform');
 await page.mouse.move(graph.x+50,graph.y+graph.height-30);await page.mouse.down();await page.mouse.move(graph.x+100,graph.y+graph.height-60);await page.mouse.up();
 if(before===await page.locator('svg.graph > g').getAttribute('transform'))throw Error('Pan did not move graph');
 await page.getByLabel('Graph source').selectOption('export');
 await expect(page.locator('.op-node').first()).toBeVisible();
 await page.getByRole('button',{name:'Fit scope',exact:true}).click();
 await page.locator('.op-node').first().click();
 await page.screenshot({path:'../docs/computation.png',fullPage:true});
 await page.getByRole('button',{name:'Hierarchy',exact:true}).click();
 await page.getByRole('button',{name:'Model root',exact:true}).click();
 await page.getByLabel('Module origin filter').selectOption('library');
 await page.locator('.tree-name').filter({hasText:'norm1'}).first().click();
 await expect(page.locator('.details .badge')).toHaveText('framework');
 await page.getByLabel('Module origin filter').selectOption('all');
 await page.getByRole('button',{name:'Model root',exact:true}).click();
 await page.screenshot({path:'../docs/explorer.png',fullPage:true});
 // Reuse the real graph as a large-IR fixture to verify bounded rendering.
 const fixture=await (await page.request.get(new URL('/api/model',page.url()).href)).json();
 const runtime=fixture.operations.filter(o=>o.graph==='runtime');
 fixture.operations=Array.from({length:12},(_,i)=>runtime.map(o=>({...o,id:`large${i}_${o.id}`}))).flat();
 fixture.data_edges=[];
 await page.route('**/api/model',route=>route.fulfill({json:fixture}));
 await page.reload();
 await page.getByRole('button',{name:'Computation',exact:true}).click();
 await page.getByRole('button',{name:'Raw graph',exact:true}).click();
 await expect(page.locator('.op-node')).toHaveCount(120);
 await page.getByRole('button',{name:'Show more (up to 500)',exact:true}).click();
 await expect(page.locator('.op-node')).toHaveCount(240);
 await page.getByRole('checkbox',{name:'Executed only',exact:true}).check();
 await expect(page.locator('.op-node')).toHaveCount(240);
 if(errors.length)throw Error(errors.join('\n'));
 console.log('PASS: hierarchy, repeated blocks, shapes, parameters, origins, runtime/export graphs, operations, tensors, zoom, pan, filters, large-graph node limits, no browser errors');
}finally{await browser.close()}
