// Real browser acceptance. Requires p2i demo MODEL --edit on P2I_URL.
import {chromium,expect} from '@playwright/test';
const model=process.env.P2I_DEMO??'transformer';
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1600,height:1100}});const errors=[];
page.on('pageerror',e=>errors.push(String(e)));
page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('favicon'))errors.push(m.text())});
try{
 await page.goto(process.env.P2I_URL??'http://127.0.0.1:8000');
 await expect(page.locator('.explore-overview')).toBeVisible();
 const paths=model==='transformer'?['blocks','blocks.0','blocks.0.attention']:model==='cnn'?['features','features.0']:['layers','layers.0'];
 for(const path of paths)await page.getByRole('button',{name:`Explore ${path}`,exact:true}).click();
 const focused=await page.locator('.scope h2').textContent();
 await page.getByRole('button',{name:'Computation',exact:true}).click();
 await page.locator('.op-node').first().click();
 await expect(page.locator('.operation-explainer')).toBeVisible();
 await page.locator('.operation-tensors button').first().click();
 await expect(page.locator('.details')).toContainText('Shape');
 await page.getByRole('button',{name:'Runtime',exact:true}).click();
 await expect(page.locator('.scope h2')).toHaveText(focused);
 await expect(page.locator('.current-call')).toBeVisible();
 await page.getByRole('button',{name:'Next',exact:true}).click({trial:true}).catch(()=>{});
 await page.getByRole('button',{name:'Explore',exact:true}).click();
 await expect(page.locator('.scope h2')).toHaveText(focused);
 await page.locator('.breadcrumbs button').first().click();
 const target=model==='transformer'?'norm':model==='cnn'?'features':'layers';
 await page.getByRole('button',{name:`Explore ${target}`,exact:true}).click();
 if(model!=='transformer')await page.getByRole('button',{name:`Explore ${target}.0`,exact:true}).click();
 await page.getByRole('button',{name:'Edit',exact:true}).click();
 const parameter=model==='transformer'?'eps':'bias';
 await page.getByLabel('Constructor parameter',{exact:true}).selectOption(parameter);
 if(model==='transformer')await page.getByLabel('Proposed value',{exact:true}).fill('0.001');
 else await page.getByLabel('Proposed value',{exact:true}).selectOption('false');
 await page.getByRole('button',{name:'Preview & validate',exact:true}).click();
 await expect(page.locator('.validation-result')).toContainText('Validation passed');
 await expect(page.locator('.diff-table')).toContainText(`parameters.${parameter}`);
 await expect(page.locator('.local')).toContainText('architecture r0 / observed r0');
 await page.getByRole('button',{name:'Commit edit',exact:true}).click();
 await expect(page.locator('.revision-list')).toContainText('r1');
 await expect(page.locator('.pending-banner')).toContainText('still shows observed r0');
 await page.getByRole('button',{name:'Build & Re-trace',exact:true}).click();
 await expect(page.locator('.local')).toContainText('architecture r1 / observed r1',{timeout:30000});
 await expect(page.locator('.pending-banner')).toHaveCount(0);
 const state=await (await page.request.get(new URL('/api/harness',page.url()).href)).json();
 if(state.summary.revision!==1||state.summary.observed_revision!==1)throw Error('Revision/observation mismatch');
 const edited=state.architecture.nodes.find(n=>n.qualified_name===(model==='transformer'?'norm':`${target}.0`));
 if(edited.parameters[parameter] !== (model==='transformer'?.001:false))throw Error('Constructor did not change');
 await page.getByRole('button',{name:'Explore',exact:true}).click();
 await page.screenshot({path:`../docs/phase2-${model}.png`,fullPage:true});
 if(errors.length)throw Error(errors.join('\n'));
 console.log(`PASS ${model}: overview, drill-down, computation, tensor, breadcrumbs, selection, preview, validation, commit, history, build/retrace, observed revision`);
}finally{await browser.close()}
